version: "3.7"

services:
    las_api-django-dev:
        build:
            context: ./django
            dockerfile: Dockerfile-dev
        image: las_api/django-dev
        env_file:
            - ./.env
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./django:/usr/src/app/
        ports:
            - 8000:8000
