version: "3.7"

services:
    green_web1:
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-django:latest
        container_name: las-django-green1
        env_file:
            - ./.env
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py collectstatic --no-input &&
                   gunicorn las_api.wsgi:application --bind 0.0.0.0:8000 --workers 3 -t 60"
        volumes:
            - static_volume:/home/app/static/
        expose:
            - "8000"
    green_web2:
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-django:latest
        container_name: las-django-green2
        env_file:
            - ./.env
        command: >
            sh -c "python manage.py collectstatic --no-input &&
                   gunicorn las_api.wsgi:application --bind 0.0.0.0:8000 --workers 3 -t 60"
        volumes:
            - static_volume:/home/app/static/
        expose:
            - "8000"

volumes:
    static_volume:
