version: "3.7"

services:
    web:
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-django:latest
        env_file:
            - ./.env.prod
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py collectstatic --no-input &&
                   gunicorn las_api.wsgi:application --bind 0.0.0.0:8000 --workers 3 -t 60"
        volumes:
            - static_volume:/home/app/static/
        scale: 2
        ports:
            - 8000-8001:8000
    nginx:
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-nginx:latest
        volumes:
            - static_volume:/home/app/static/
        ports:
            - 80
        healthcheck:
            test: [ "CMD", "nc", "-vz", "-w1", "localhost", "80" ]
            interval: 1s
            timeout: 1s
            retries: 30
        depends_on:
            - web

volumes:
    static_volume:
