version: "3.7"

services:
    web:
        build:
            context: ./django
            dockerfile: Dockerfile
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-django:latest
        env_file:
            - ./.env.prod
        volumes:
            - static_volume:/home/app/static
        entrypoint:
            - /docker-entrypoint.sh
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-nginx:latest
        volumes:
            - static_volume:/home/app/static/
        ports:
            - 80:80
        depends_on:
            - web
        entrypoint:
            - /docker-entrypoint.sh

volumes:
    static_volume:
