version: "3.7"

services:
    web:
        build:
            context: ./django
            dockerfile: Dockerfile
        image: 623026104123.dkr.ecr.ap-northeast-2.amazonaws.com/las-django:latest
        env_file:
            - ./.env.prod
        command: gunicorn las_api.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - static_volume:/home/app/static/
        expose:
            - 8000

volumes:
    static_volume:
